"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import "@near-wallet-selector/modal-ui/styles.css";
import DataProvider from "@/providers/data";
const inter = Inter({ subsets: ["latin"] });
import { WalletProvider } from "@/providers/WalletProvider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// flex flex-1 flex-col min-h-screen text-gray-500 gradient w-full  h-full flex justify-center items-center bold text-white

const MintbaseWalletSetup = {
  contractAddress: "ncrcoursencr.mintspace2.testnet",
  network: "testnet" as any,
  callbackUrl: "http://localhost:3000/",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WalletProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="">
            <DataProvider>{children}</DataProvider>
            <Toaster />
          </div>
        </body>
      </html>
    </WalletProvider>
  );
}
